MAKE="make TARGET=${kernelver}"
CLEAN="make clean"
PACKAGE_NAME="oxp-sensors"
PACKAGE_VERSION="v0.9.0.gf75d844"
BUILT_MODULE_NAME[0]="oxp-sensors"
DEST_MODULE_LOCATION[0]="/kernel/drivers/hwmon"
AUTOINSTALL="yes"
